name: "Podcast Generator 0233"
author: "Jordan Gregory-Wallis"
description: "Generates a feed fora a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: "The commiter's emails"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "The commiter's name"
    required: true
    default: ${{ github.actor }}
